'use client'

import Link from 'next/link'
import { AdminStatusBadge } from '@/components/admin/AdminStatusBadge'
import { Card } from '@/components/ui/Card'
import { useMockAdminOrders } from '@/hooks/useMockAdminOrders'
import { formatPriceInBRL } from '@/lib/formatters'
import { adminOrderStatuses, adminOrderStatusLabels } from '@/types/admin'

function formatDate(value: string) {
  return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}

export function AdminOrderDetail({ orderId }: { orderId: string }) {
  const { orders, updateOrderStatus } = useMockAdminOrders()
  const order = orders.find((candidate) => candidate.id === orderId)
  if (!order) return <Card className="p-6"><p className="text-sm text-steel">Pedido demonstrativo não encontrado nesta sessão.</p><Link className="mt-4 inline-block text-sm font-semibold text-cyan" href="/admin">Voltar aos pedidos</Link></Card>

  return <div>
    <Link className="text-sm font-semibold text-cyan hover:text-slate" href="/admin">← Voltar aos pedidos</Link>
    <div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-cyan">Pedido demonstrativo</p><h1 className="mt-2 font-display text-4xl font-semibold text-slate">{order.number}</h1><p className="mt-2 text-sm text-steel">Criado em {formatDate(order.createdAt)}</p></div><AdminStatusBadge status={order.status} /></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.5fr_0.9fr]">
      <div className="space-y-5">
        <Card className="p-5 sm:p-6"><h2 className="font-display text-2xl font-semibold text-slate">Itens e personalização</h2><div className="mt-5 space-y-5">{order.items.map((item) => <div className="border-t border-mist pt-5 first:border-t-0 first:pt-0" key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold text-slate">{item.productName}</h3><p className="mt-1 text-sm text-steel">{item.quantity} × {formatPriceInBRL(item.unitPrice)}</p></div><p className="font-semibold text-slate">{formatPriceInBRL(item.total)}</p></div>{item.customization && <div className="mt-4 rounded-xl bg-sterile p-4 text-sm"><p className="font-semibold text-slate">Resumo de personalização</p><dl className="mt-3 grid gap-2 text-steel">{item.customization.name && <div><dt className="inline font-medium text-slate">Nome: </dt><dd className="inline">{item.customization.name}</dd></div>}{item.customization.phrase && <div><dt className="inline font-medium text-slate">Frase: </dt><dd className="inline">{item.customization.phrase}</dd></div>}{item.customization.date && <div><dt className="inline font-medium text-slate">Data: </dt><dd className="inline">{item.customization.date}</dd></div>}{item.customization.notes && <div><dt className="inline font-medium text-slate">Observações: </dt><dd className="inline">{item.customization.notes}</dd></div>}{item.customization.musicLink && <div><dt className="inline font-medium text-slate">Música: </dt><dd className="inline break-all">{item.customization.musicLink}</dd></div>}</dl></div>}{item.files.length > 0 && <div className="mt-4"><p className="text-sm font-semibold text-slate">Arquivos selecionados (metadados)</p><ul className="mt-2 space-y-2">{item.files.map((file) => <li className="rounded-xl border border-mist p-3 text-xs text-steel" key={file.id}><p className="font-semibold text-slate">{file.originalFileName}</p><p className="mt-1 break-all">{file.mimeType} · {Math.round(file.fileSize / 1000)} KB · {file.storagePath}</p></li>)}</ul></div>}</div>)}</div></Card>
        <Card className="p-5 sm:p-6"><h2 className="font-display text-2xl font-semibold text-slate">Histórico</h2><ol className="mt-5 space-y-4 border-l border-cyan/50 pl-5">{order.history.map((entry) => <li className="relative" key={entry.id}><span className="absolute -left-[25px] top-1.5 size-2 rounded-full bg-cyan" /><p className="text-sm font-semibold text-slate">{adminOrderStatusLabels[entry.status]}</p><p className="mt-1 text-sm text-steel">{entry.description}</p><p className="mt-1 text-xs text-steel">{formatDate(entry.createdAt)}</p></li>)}</ol></Card>
      </div>
      <div className="space-y-5"><Card className="p-5"><h2 className="font-display text-2xl font-semibold text-slate">Status</h2><label className="mt-4 block text-sm font-semibold text-slate" htmlFor="order-status">Produção e atendimento<select className="mt-2 w-full rounded-xl border border-mist bg-white px-3 py-3 font-normal text-galanta-black outline-none focus:border-cyan" id="order-status" onChange={(event) => updateOrderStatus(order.id, event.target.value as typeof order.status)} value={order.status}>{adminOrderStatuses.map((status) => <option key={status} value={status}>{adminOrderStatusLabels[status]}</option>)}</select></label><p className="mt-3 text-xs leading-5 text-steel">A mudança é salva somente no localStorage deste navegador.</p></Card>
        <Card className="p-5"><h2 className="font-display text-2xl font-semibold text-slate">Cliente</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-steel">Nome</dt><dd className="font-medium text-slate">{order.customer.fullName}</dd></div><div><dt className="text-steel">Contato</dt><dd className="font-medium text-slate">{order.customer.email}<br />{order.customer.phone}</dd></div><div><dt className="text-steel">Documento</dt><dd className="font-medium text-slate">{order.customer.document}</dd></div></dl></Card>
        <Card className="p-5"><h2 className="font-display text-2xl font-semibold text-slate">Resumo</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-steel">Subtotal</dt><dd>{formatPriceInBRL(order.subtotal)}</dd></div><div className="flex justify-between"><dt className="text-steel">Entrega</dt><dd>{formatPriceInBRL(order.shippingTotal)}</dd></div><div className="flex justify-between border-t border-mist pt-3 font-semibold text-slate"><dt>Total</dt><dd>{formatPriceInBRL(order.total)}</dd></div><div className="pt-2"><dt className="text-steel">Pagamento</dt><dd className="mt-1 font-medium text-slate">{order.paymentStatus}</dd></div>{order.trackingCode && <div><dt className="text-steel">Rastreio</dt><dd className="mt-1 font-medium text-slate">{order.trackingCode}</dd></div>}</dl></Card>
        {(order.customerNotes || order.internalNotes || order.utms) && <Card className="p-5"><h2 className="font-display text-2xl font-semibold text-slate">Contexto</h2>{order.customerNotes && <p className="mt-4 text-sm text-steel"><strong className="text-slate">Cliente: </strong>{order.customerNotes}</p>}{order.internalNotes && <p className="mt-3 text-sm text-steel"><strong className="text-slate">Interno: </strong>{order.internalNotes}</p>}{order.utms && <dl className="mt-4 border-t border-mist pt-4 text-xs text-steel">{Object.entries(order.utms).map(([key, value]) => <div className="mt-1" key={key}><dt className="inline font-semibold text-slate">{key}: </dt><dd className="inline">{value}</dd></div>)}</dl>}</Card>}
      </div>
    </div>
  </div>
}
